name: coffe_shop_mobile_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  #d
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5

  #model
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  #UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  flutter_svg: ^2.0.16
  flutter_native_splash: ^2.4.3

  #State Management
  provider: ^6.1.2
  #Bloc
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  #hydrated_bloc: ^9.1.5
  meta: ^1.15.0
  #Firebase
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  #very_good_analysis
  very_good_analysis: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/profile/
    - assets/image/
    - assets/image/banner/
    - assets/image/coffee/
    - assets/image/splash/
    - assets/image/splash/
    - assets/image/native/


flutter_native_splash:
  # Arka plan rengi
  color: "#ffffff"  # Açık mavi
  # Karanlık mod arka plan rengi
  color_dark: "#111111"  # Koyu mavi

  # Splash ekranında kullanılacak görüntü (PNG formatında)
  image: "assets/image/native/native (1).png"
  image_dark: "assets/image/native/native (1).png"

  # Android 12 ve sonrası için özel ayarlar
  android_12:
    # Splash ekranında kullanılacak ikon
    image: "assets/image/native/native (1).png"
    # İkonun arka plan rengi
    icon_background_color: "#ffffff"
    # Karanlık mod ikon arka plan rengi
    icon_background_color_dark: "#111111"

  # Android ekran yönlendirme (isteğe bağlı)
  android_screen_orientation: sensorPortrait

  # Splash ekranı tam ekran mı olacak?
  fullscreen: true

  # Platforma özel ayarlar
  color_android: "#ffffff"
  color_dark_android: "#111111"
  image_android: "assets/image/native/native (1).png"
  image_dark_android: "assets/image/native/native (1).png"

