name: coffe_shop_mobile_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  #d
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5

  #model
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  #UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  flutter_svg: ^2.0.16

  #State Management
  provider: ^6.1.2
  #Bloc
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  #hydrated_bloc: ^9.1.5
  meta: ^1.15.0
  #Firebase
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  #very_good_analysis
  very_good_analysis: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/icon/bottomnavbaricon/
    - assets/image/banner/
    - assets/coffee/ebk/
    - assets/coffee/sk/
    - assets/coffee/stk/
    - assets/image/splash/
    - assets/lottie/lottieee.json
